"""
I-0321: Hostile rendered-page visual QA and proofread pass.

Samples page images across openings, visual pages, tables, source surfaces,
logos/people, dense chapters, and closing pages. Records cut/keep/fix decisions.
"""
import fitz  # PyMuPDF
import os, hashlib, json, csv
from pathlib import Path
from datetime import datetime

BASE = Path("C:/AI/TEMP/World_Of_Computing")
PDF_IN = BASE / "rendered/final_private_i0320/Next-Token-final-private-quantitative-i0320.pdf"
OUT_DIR = BASE / "rendered/final_private_i0321"
OUT_DIR.mkdir(parents=True, exist_ok=True)
PAGE_IMG_DIR = OUT_DIR / "page_samples"
PAGE_IMG_DIR.mkdir(exist_ok=True)

# Chapter bounds from I-0320 manifest - approximate page ranges from previous work
CHAPTER_INFO = [
    (1, "Before the Transformer", "early technical"),
    (2, "Attention Catches Fire", "early technical"),
    (3, "The Scaling Bet", "early technical"),
    (4, "Pre-training as Platform", "early technical / platform"),
    (5, "GPT-1 to GPT-3: The Door Opens", "platform / company"),
    (6, "Alignment Enters the Product", "company / mechanism"),
    (7, "ChatGPT: The Interface Event", "company / product"),
    (8, "Microsoft: The Cloud Bargain", "company / platform"),
    (9, "Google, DeepMind, and Gemini", "company / product"),
    (10, "Meta, Llama, and the Open-Weight Shock", "company / open"),
    (11, "Chinese Frontier and Open Models", "company / frontier"),
    (12, "Europe, xAI, and the Rest of the Frontier", "company / frontier"),
    (13, "Model Rankings: How We Measured", "benchmark / method"),
    (14, "NVIDIA and the CUDA Moat", "hardware / company"),
    (15, "GTC 2026: The AI Factory Sells Itself", "hardware / event"),
    (16, "Speed to Power", "hardware / infrastructure"),
    (17, "Data, Tokens, and the Library Problem", "data / mechanism"),
    (18, "Tools, Retrieval, and the Agent Turn", "tools / mechanism"),
    (19, "Code as the Second Native Language", "code / mechanism"),
    (20, "Claude Code: Industrialized Pair Programming", "code / company"),
    (21, "Reasoning, Test-Time Compute, and the New Scaling Axis", "reasoning / mechanism"),
    (22, "Economics of Intelligence on Tap", "economics / mechanism"),
    (23, "Failure Modes, Truth, and Trust", "trust / mechanism"),
    (24, "Next Token", "synthesis"),
]

# Forbidden strings to check in extracted text
FORBIDDEN = [
    r"C:/", r"file:///", r"local path", r"private-edition", r"project ledgers",
    r"Use note", r"Boundary:", r"Blocked claims", r"Source/provenance",
    r"private-edition visual layer", r"source boundaries",
    r"F01.", r"A-0", r"VX", r"S-0", r"C-0", r"sha256",
    r"generated by an AI", r"AI-generated", r"workflow",
    r"Visual Portfolio", r"PORTFOLIO PLATE",
    r"assets_manifest", r"champion/", r"manuscript/", r"data/",
    r"rendered/", r"scripts/",
]

# Chapter type -> sampling strategy
SAMPLING = {
    "early technical": 4,    # pages: first, mid-chapter visual, last
    "platform / company": 5,
    "company / mechanism": 4,
    "company / product": 5,
    "company / open": 4,
    "company / frontier": 4,
    "benchmark / method": 4,
    "hardware / company": 4,
    "hardware / event": 5,
    "hardware / infrastructure": 5,
    "data / mechanism": 4,
    "tools / mechanism": 4,
    "code / mechanism": 4,
    "code / company": 4,
    "reasoning / mechanism": 4,
    "economics / mechanism": 4,
    "trust / mechanism": 4,
    "synthesis": 5,
}

def find_chapter_pages(doc, chap_num):
    """Find page range for a chapter by searching chapter headings in text."""
    heading_markers = [
        f"Chapter {chap_num}",
        f"CHAPTER {chap_num}",
    ]
    
    start_page = None
    end_page = None
    
    for i in range(len(doc)):
        page = doc[i]
        text = page.get_text()
        for marker in heading_markers:
            if marker in text and ("Chapter " + str(chap_num+1)) not in text[:200]:
                if start_page is None:
                    start_page = i
                break
        
        # Check for next chapter
        next_marker = f"Chapter {chap_num+1}"
        if start_page is not None and next_marker in text:
            end_page = i
            break
    
    if start_page is None:
        return None, None
    if end_page is None:
        end_page = len(doc) - 1
    
    return start_page, end_page

def sample_pages(doc, start, end, num_samples):
    """Sample pages from a range: first, last, and evenly spaced middle pages."""
    if start is None or end is None or end <= start:
        return []
    
    pages = []
    # Always include first page of chapter
    pages.append(start)
    
    if num_samples >= 3:
        # Middle pages
        mid_start = start + 1
        mid_end = end - 1
        middle_count = num_samples - 2
        if middle_count > 0 and mid_end > mid_start:
            step = max(1, (mid_end - mid_start) // (middle_count + 1))
            for p in range(mid_start + step, mid_end, step):
                if len(pages) < num_samples - 1:
                    pages.append(p)
    
    # Always include last page of chapter
    if end > start and end not in pages:
        pages.append(end)
    
    return sorted(set(pages))[:num_samples]

def render_page_image(doc, page_num, prefix):
    """Render a page as a PNG image for visual inspection."""
    page = doc[page_num]
    # 2x zoom for readability
    mat = fitz.Matrix(2.0, 2.0)
    pix = page.get_pixmap(matrix=mat)
    out_path = PAGE_IMG_DIR / f"{prefix}_p{page_num+1:03d}.png"
    pix.save(str(out_path))
    return out_path

def check_page_text(text, page_num):
    """Check page text for forbidden strings and quality issues."""
    issues = []
    
    # Forbidden strings
    found = []
    for f in FORBIDDEN:
        if f.lower() in text.lower():
            found.append(f)
    if found:
        issues.append({"type": "forbidden_strings", "page": page_num, "found": found})
    
    # AI-generated or process language
    ai_language = ["generated by", "workflow", "assembly", "pass I-", "scoreboard",
                   "ideas.tsv", "ledger", "manifest"]
    ai_found = [w for w in ai_language if w.lower() in text.lower()]
    if ai_found:
        issues.append({"type": "process_language", "page": page_num, "found": ai_found})
    
    # Check if page is very short (sparse)
    text_stripped = text.strip()
    if len(text_stripped) < 100:
        issues.append({"type": "sparse_page", "page": page_num, "chars": len(text_stripped)})
    elif len(text_stripped) < 300:
        issues.append({"type": "light_page", "page": page_num, "chars": len(text_stripped)})
    
    return issues

def check_page_visuals(doc, page_num):
    """Check page for visual issues."""
    page = doc[page_num]
    issues = []
    
    # Count images
    images = page.get_images()
    image_count = len(images)
    
    # Multi-image pages
    if image_count > 1:
        # Check if they're small/icon vs real images
        real_images = 0
        for img in images:
            xref = img[0]
            base_image = doc.extract_image(xref)
            w, h = base_image.get("width", 0), base_image.get("height", 0)
            if w > 100 and h > 100:  # Not a tiny icon
                real_images += 1
        if real_images > 1:
            issues.append({"type": "multi_image_page", "page": page_num, "count": real_images})
    
    # Check drawings
    drawings = page.get_drawings()
    
    # No image and little text = potentially blank/sparse page
    if image_count == 0:
        text = page.get_text().strip()
        if len(text) < 200:
            issues.append({"type": "no_visual_sparse", "page": page_num, "text_chars": len(text)})
    
    return issues

def main():
    print("I-0321: Hostile page QA")
    print(f"PDF: {PDF_IN}")
    
    doc = fitz.open(str(PDF_IN))
    total_pages = len(doc)
    print(f"Total pages: {total_pages}")
    
    # Step 1: Extract all text for global scan
    print("\n--- Global text scan ---")
    all_text = ""
    for i in range(total_pages):
        all_text += doc[i].get_text() + "\n---PAGE_BREAK---\n"
    
    # Check forbidden strings globally
    global_issues = []
    for f in FORBIDDEN:
        count = all_text.lower().count(f.lower())
        if count > 0:
            global_issues.append({"string": f, "count": count})
    
    print(f"Global forbidden string hits: {len(global_issues)}")
    for gi in global_issues:
        print(f"  '{gi['string']}': {gi['count']} occurrences")
    
    # Step 2: Find chapter page ranges
    print("\n--- Chapter page ranges ---")
    chapter_ranges = {}
    page_map = {}  # page_num -> chapter guess
    
    for i in range(total_pages):
        text = doc[i].get_text()
        for ch_num, ch_name, ch_type in CHAPTER_INFO:
            heading_markers = [
                f"Chapter {ch_num}\n",
                f"Chapter {ch_num} ",
                f"CHAPTER {ch_num}",
                f"{ch_num}\n{ch_name}",
            ]
            for marker in heading_markers:
                if marker in text[:500]:
                    if ch_num not in chapter_ranges:
                        chapter_ranges[ch_num] = i
    
    # Sort and compute ranges
    sorted_chapters = sorted(chapter_ranges.items())
    chapter_spans = {}
    for idx, (ch_num, start) in enumerate(sorted_chapters):
        if idx + 1 < len(sorted_chapters):
            end = sorted_chapters[idx + 1][1] - 1
        else:
            end = total_pages - 1
        chapter_spans[ch_num] = (start, end)
        ch_info = [c for c in CHAPTER_INFO if c[0] == ch_num]
        ch_name = ch_info[0][1] if ch_info else f"Chapter {ch_num}"
        print(f"  Chapter {ch_num:2d}: p{start+1:3d}-p{end+1:3d} ({end-start+1:3d}pp) - {ch_name}")
    
    # Build page->chapter map
    for ch_num, (start, end) in chapter_spans.items():
        for p in range(start, end + 1):
            page_map[p] = ch_num
    
    # Step 3: Sample and inspect pages
    print("\n--- Page sampling and inspection ---")
    all_issues = []
    sampled_pages = set()
    
    for ch_num, ch_name, ch_type in CHAPTER_INFO:
        if ch_num not in chapter_spans:
            continue
        start, end = chapter_spans[ch_num]
        num_samples = SAMPLING.get(ch_type, 4)
        pages = sample_pages(doc, start, end, num_samples)
        
        for p in pages:
            if p in sampled_pages:
                continue
            sampled_pages.add(p)
            
            # Render page image
            prefix = f"ch{ch_num:02d}"
            img_path = render_page_image(doc, p, prefix)
            
            # Check text
            text = doc[p].get_text()
            text_issues = check_page_text(text, p)
            all_issues.extend(text_issues)
            
            # Check visuals
            visual_issues = check_page_visuals(doc, p)
            all_issues.extend(visual_issues)
            
            issue_types = set(i["type"] for i in text_issues + visual_issues)
            if issue_types:
                print(f"  p{p+1:3d} Ch{ch_num:2d} [{ch_type[:20]}]: {issue_types}")
    
    print(f"\nSampled {len(sampled_pages)} pages from {len(chapter_spans)} chapters")
    print(f"Total issues found: {len(all_issues)}")
    
    # Step 4: Categorize issues by type
    issue_counts = {}
    for issue in all_issues:
        t = issue["type"]
        issue_counts[t] = issue_counts.get(t, 0) + 1
    
    print("\n--- Issue summary ---")
    for t, c in sorted(issue_counts.items()):
        print(f"  {t}: {c}")
    
    # Step 5: Also sample dense/visual-heavy pages specifically
    print("\n--- Visual-heavy page inspection ---")
    visual_pages = []
    for i in range(total_pages):
        page = doc[i]
        images = page.get_images()
        if len(images) > 0:
            visual_pages.append((i, len(images)))
    
    print(f"Pages with images: {len(visual_pages)}")
    
    # Sample visual pages across the book
    if visual_pages:
        step = max(1, len(visual_pages) // 15)
        for idx in range(0, len(visual_pages), step):
            if idx >= len(visual_pages):
                break
            p, img_count = visual_pages[idx]
            if p not in sampled_pages:
                prefix = "vis"
                img_path = render_page_image(doc, p, prefix)
                sampled_pages.add(p)
                
                text = doc[p].get_text()
                text_issues = check_page_text(text, p)
                visual_issues = check_page_visuals(doc, p)
                all_issues.extend(text_issues + visual_issues)
    
    # Step 6: Check opening pages and closing pages specifically
    print("\n--- Opening/first-page QA ---")
    for ch_num, start, end in [(cn, s, e) for cn, (s, e) in sorted(chapter_spans.items())]:
        p = start
        if p not in sampled_pages:
            prefix = f"open{ch_num:02d}"
            img_path = render_page_image(doc, p, prefix)
            sampled_pages.add(p)
            text = doc[p].get_text()
            text_issues = check_page_text(text, p)
            all_issues.extend(text_issues)
    
    # Check last 3 pages
    print("--- Closing pages QA ---")
    for p in range(max(0, total_pages - 3), total_pages):
        if p not in sampled_pages:
            prefix = "close"
            img_path = render_page_image(doc, p, prefix)
            sampled_pages.add(p)
            text = doc[p].get_text()
            all_issues.extend(check_page_text(text, p))
    
    # Step 7: Write results
    print(f"\n--- Final stats ---")
    print(f"Total pages: {total_pages}")
    print(f"Sampled pages: {len(sampled_pages)}")
    print(f"Total issues: {len(all_issues)}")
    
    # Re-count issue types after all sampling
    final_issue_counts = {}
    for issue in all_issues:
        t = issue["type"]
        final_issue_counts[t] = final_issue_counts.get(t, 0) + 1
    
    # Write TSV output
    qa_path = BASE / "data/hostile_page_qa_i0321.tsv"
    with open(qa_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter="\t")
        writer.writerow(["page_num", "chapter", "sample_type", "issue_type", "detail"])
        for issue in all_issues:
            ch = page_map.get(issue["page"], "?")
            detail = str(issue.get("found", issue.get("chars", issue.get("count", ""))))
            writer.writerow([issue["page"]+1, f"Ch{ch}", "", issue["type"], detail])
    
    # Write summary
    summary_path = BASE / "data/hostile_page_qa_summary_i0321.tsv"
    with open(summary_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter="\t")
        writer.writerow(["metric", "value"])
        writer.writerow(["total_pages", total_pages])
        writer.writerow(["sampled_pages", len(sampled_pages)])
        writer.writerow(["total_issues", len(all_issues)])
        writer.writerow(["global_forbidden_hits", len(global_issues)])
        writer.writerow(["image_pages", len(visual_pages)])
        for t, c in sorted(final_issue_counts.items()):
            writer.writerow([f"issue_{t}", c])
        for gi in global_issues:
            writer.writerow([f"forbidden_{gi['string']}", gi["count"]])
    
    # Write chapter-level sampling manifest
    chapter_qa_path = BASE / "data/hostile_page_qa_chapters_i0321.tsv"
    with open(chapter_qa_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter="\t")
        writer.writerow(["chapter", "name", "type", "start_page", "end_page", "pages", "sampled", "issues"])
        for ch_num, ch_name, ch_type in CHAPTER_INFO:
            if ch_num in chapter_spans:
                start, end = chapter_spans[ch_num]
                pages = end - start + 1
                ch_issues = [i for i in all_issues if page_map.get(i["page"]) == ch_num]
                sampled_count = len([p for p in sampled_pages if page_map.get(p) == ch_num])
                issue_types = set(i["type"] for i in ch_issues)
                writer.writerow([ch_num, ch_name, ch_type, start+1, end+1, pages, sampled_count,
                               ";".join(sorted(issue_types)) if issue_types else "none"])
    
    doc.close()
    
    print(f"\nOutputs:")
    print(f"  Samples: {PAGE_IMG_DIR}/")
    print(f"  Issues:  {qa_path}")
    print(f"  Summary: {summary_path}")
    print(f"  Chapters: {chapter_qa_path}")

if __name__ == "__main__":
    main()
