from __future__ import annotations

import argparse
import csv
import hashlib
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import fitz
from bs4 import BeautifulSoup, Tag


ROOT = Path(__file__).resolve().parents[1]
PASS_ID = "I-0320"
RUN_ID = "pass-0320"

SOURCE_HTML = ROOT / "rendered" / "final_private_i0319" / "Next-Token-final-private-one-visual-page-i0319.html"
SOURCE_PDF = ROOT / "rendered" / "final_private_i0319" / "Next-Token-final-private-one-visual-page-i0319.pdf"
SOURCE_MD = ROOT / "manuscript" / "Next-Token-one-visual-page-i0319.md"

OUTDIR = ROOT / "rendered" / "final_private_i0320"
HTML_OUT = OUTDIR / "Next-Token-final-private-quantitative-i0320.html"
PDF_OUT = OUTDIR / "Next-Token-final-private-quantitative-i0320.pdf"
MD_OUT = ROOT / "manuscript" / "Next-Token-quantitative-i0320.md"
REPORT = ROOT / "manuscript" / "quantitative-enrichment-i0320.md"
CHAMPION_REPORT = ROOT / "champion" / "quantitative-enrichment-i0320.md"
CHAMPION_POINTER = ROOT / "champion" / "final-private-pdf-pointer-i0320.md"

OUT_BASELINE = ROOT / "data" / "quantitative_enrichment_baseline_i0320.tsv"
OUT_TABLES = ROOT / "data" / "quantitative_enrichment_tables_i0320.tsv"
OUT_QA = ROOT / "data" / "quantitative_enrichment_qa_i0320.tsv"
OUT_MANIFEST = ROOT / "data" / "quantitative_enrichment_manifest_i0320.tsv"

README = ROOT / "README.md"
CHAMPION_README = ROOT / "champion" / "README.md"
READER_GUIDE = ROOT / "champion" / "private-reader-guide-i0311.md"
GUIDE_POINTER = ROOT / "champion" / "final-private-reader-guide-pointer-i0311.md"
IDEAS = ROOT / "ideas.tsv"
CLAIMS = ROOT / "claims.tsv"
SCOREBOARD = ROOT / "scoreboard.tsv"
INSIGHTS = ROOT / "insights.md"
ASSETS_MANIFEST = ROOT / "assets_manifest.tsv"

BACKUP_DIR = ROOT / "archive" / "champion_backup_i0320_changed_files"
BACKUP_MANIFEST = ROOT / "archive" / "champion_backup_i0320_changed_files_manifest.tsv"


FORBIDDEN_PDF_STRINGS = [
    "Visual Portfolio",
    "PORTFOLIO PLATE",
    "Image Sequence",
    "Images placed with this chapter",
    "Use note",
    "Boundary:",
    "Blocked claims",
    "Source/provenance",
    "project ledgers",
    "private-edition visual layer",
    "source boundaries",
    "F01.",
    "A-0",
    "VX",
    "S-0",
    "C-0",
    "sha256",
    "C:/",
    "file:///",
    "rescue proof",
    "placeholder",
    "generated by an AI",
    "AI-generated",
]


TABLES = [
    {
        "id": "QT-0320-01",
        "chapter": "03",
        "kind": "benchmark",
        "title": "Scaling Measurement: What The Curve Actually Measured",
        "intro": "The early scaling argument became powerful because it turned model size, data, and compute into measurable lanes instead of vague size worship.",
        "columns": ["Lane", "Number or formula", "Reader use"],
        "rows": [
            ["Model size", "N, the parameter count lane", "Bigger N can lower loss over measured ranges; it is not a product-success guarantee."],
            ["Data size", "D, the token/data lane", "More data changes the fit; Chinchilla-style reasoning made undertraining a central question."],
            ["Compute", "C, the training-compute lane", "Compute links budgets to experiments, but it does not buy truth, safety, or cheap inference by itself."],
            ["Formula shape", "Loss is read as a function of N, D, and C", "Use the equation as a map of constraints, not a prophecy."],
        ],
        "source_ids": "S-0003;S-0015;data/chapter3_scaling_claim_audit_i0094.tsv",
    },
    {
        "id": "QT-0320-02",
        "chapter": "04",
        "kind": "benchmark",
        "title": "GPT Lineage: Interface And Evaluation Steps",
        "intro": "The GPT line matters numerically because each step changed the test surface as well as the model.",
        "columns": ["Year", "Surface", "Measured or evaluated job"],
        "rows": [
            ["2018", "GPT-1", "Generative pretraining followed by supervised transfer."],
            ["2019", "GPT-2", "Prompted continuation and a staged release debate."],
            ["2020", "GPT-3", "Zero-shot, one-shot, and few-shot prompting became the central evaluation grammar."],
            ["2021", "Codex and Copilot", "Functional correctness and cursor-level code suggestions moved language models into programming."],
        ],
        "source_ids": "S-0011;S-0012;S-0013;S-0004;S-0052;S-0070;data/chapter5_gpt_lineage_claim_audit_i0095.tsv",
    },
    {
        "id": "QT-0320-03",
        "chapter": "05",
        "kind": "benchmark",
        "title": "Instruction Following: The Evaluation Shift",
        "intro": "Instruction tuning changed what counted as a good answer: the model was no longer judged only as a continuation machine.",
        "columns": ["Before", "After", "Why the number changed"],
        "rows": [
            ["Continuation likelihood", "Instruction-following behavior", "The target moved from next text to useful assistant response."],
            ["Few-shot prompts", "Preference-shaped answers", "Examples in context gave way to training for human-preferred behavior."],
            ["Benchmark score", "User-facing helpfulness", "A higher score did not automatically prove truthfulness, safety, or robustness."],
        ],
        "source_ids": "S-0014;data/chapter6_alignment_claim_audit_i0096.tsv",
    },
    {
        "id": "QT-0320-04",
        "chapter": "06",
        "kind": "benchmark",
        "title": "ChatGPT As A Measured Interface Event",
        "intro": "The ChatGPT shock was not only model capability; it was a distribution and interface event that made ordinary prompting measurable in public.",
        "columns": ["Date lane", "Reader-facing surface", "What the metric can support"],
        "rows": [
            ["November 2022", "ChatGPT public interface", "A new public assistant surface, not proof of every underlying model ability."],
            ["2022-2023", "Plus subscription and product packaging", "A consumer meter appeared; revenue, margins, and active-use totals need separate evidence."],
            ["2023", "Enterprise and API surfaces", "Distribution channels multiplied; adoption claims still need customer-side data."],
        ],
        "source_ids": "S-0006;S-0078;S-0090;data/chapter7_chatgpt_completion_audit_i0097.tsv;data/chapter22_economics_claim_audit_i0127.tsv",
    },
    {
        "id": "QT-0320-05",
        "chapter": "09",
        "kind": "benchmark",
        "title": "2024 Benchmark Landscape: Long Context And Multimodal Pressure",
        "intro": "By 2024, benchmark tables were no longer one column of text scores; they mixed modality, context length, coding, and model-family claims.",
        "columns": ["Year", "Model or surface", "Benchmark lane"],
        "rows": [
            ["2024", "Gemini and Gemini 1.5", "Multimodal and long-context report surfaces."],
            ["2024", "Llama 3 and Mixtral", "Open-weight and mixture-of-experts comparison surfaces."],
            ["2024", "SWE-bench and LiveCodeBench", "Coding and issue-resolution benchmark surfaces."],
        ],
        "source_ids": "data/benchmark_model_landscape_rows_i0289.tsv;data/benchmark_model_landscape_tables_i0289.tsv",
    },
    {
        "id": "QT-0320-06",
        "chapter": "10",
        "kind": "benchmark",
        "title": "Open-Weight Evaluation: What A Model Card Can Prove",
        "intro": "Open weights widened inspection, but model-card rows still had to be read as scoped evidence, not as live rank or legal permission.",
        "columns": ["Surface", "Evaluation job", "Do not infer"],
        "rows": [
            ["Llama 2 and Code Llama", "Foundation and code-model eval tables", "That open weights are automatically open source or safe."],
            ["Mistral 7B", "Efficient-model comparison surface", "Broad superiority or adoption."],
            ["Hugging Face model cards", "Distribution and benchmark context", "Current deployment, legal openness, or live rank."],
        ],
        "source_ids": "data/benchmark_model_landscape_rows_i0289.tsv;data/model_card_benchmark_completion_i0289.tsv",
    },
    {
        "id": "QT-0320-07",
        "chapter": "12",
        "kind": "benchmark",
        "title": "2025 China And Open-Model Benchmark Lanes",
        "intro": "The 2025 landscape becomes legible when the reader separates reasoning reports, model cards, and leaderboards instead of merging them into one crown.",
        "columns": ["Year", "Surface", "Benchmark lane"],
        "rows": [
            ["2025", "DeepSeek-V3 and R1", "Reasoning and open-model benchmark surfaces."],
            ["2025", "Qwen, GLM, and Kimi", "China frontier and open-model model-card lanes."],
            ["2025", "Claude, Gemini, and OpenAI docs", "Provider docs as mutable version surfaces."],
        ],
        "source_ids": "data/benchmark_model_landscape_rows_i0289.tsv;data/chapter11_china_open_model_claim_audit_i0105.tsv",
    },
    {
        "id": "QT-0320-08",
        "chapter": "13",
        "kind": "benchmark",
        "title": "Benchmark Ladder Through The Cutoff",
        "intro": "The book's ranking chapter now has a year-by-year spine so model claims stay dated and scoped.",
        "columns": ["Year", "Surface", "Reader job"],
        "rows": [
            ["2018", "GPT-1", "Pretraining transfer."],
            ["2019", "GPT-2", "Staged release and prompted continuation."],
            ["2020", "GPT-3", "Few-shot prompting and API turn."],
            ["2021", "Codex and Copilot", "Code interface."],
            ["2022", "ChatGPT", "Assistant interface."],
            ["2023", "GPT-4, Llama, Claude", "Frontier and open-weight split."],
            ["2024", "Gemini, Llama 3, Claude 3", "Model-family competition."],
            ["2025", "DeepSeek-R1, GPT-4.1, Claude Code", "Reasoning and coding surface."],
            ["2026", "Cutoff landscape", "Dated roadmap and leaderboard pressure."],
        ],
        "source_ids": "data/benchmark_year_table_i0283.tsv",
    },
    {
        "id": "QT-0320-09",
        "chapter": "13",
        "kind": "benchmark",
        "title": "Arena Rank: What A Dated Slice Can And Cannot Say",
        "intro": "A leaderboard is useful only when the date, category, and split travel with the number.",
        "columns": ["Evidence lane", "Number or date", "Reader use"],
        "rows": [
            ["LMArena text-style-control slice", "Published 2026-05-19", "A historical preference-rank snapshot, not a live cutoff-day crown."],
            ["Top rows", "Top twelve shown in the local chart package", "A crowded frontier view, not a universal quality score."],
            ["Confidence overlap", "Shared uncertainty bands", "A warning against turning a narrow rank into a total model hierarchy."],
        ],
        "source_ids": "S-0080;data/chapter13_rankings_expansion_claim_audit_i0098.tsv;data/lmarena_may19_chart_i0034.tsv",
    },
    {
        "id": "QT-0320-10",
        "chapter": "20",
        "kind": "benchmark",
        "title": "Coding-Agent Benchmarks: Harness Before Hype",
        "intro": "Coding-agent numbers are interesting only if the benchmark, scaffold, and tool permissions remain visible.",
        "columns": ["Surface", "Reported number", "How to read it"],
        "rows": [
            ["Claude Opus 4 on SWE-bench", "72.5 percent, vendor-reported", "A reported benchmark result, not workplace productivity."],
            ["Claude Opus 4 on Terminal-bench", "43.2 percent, vendor-reported", "A terminal-harness result, not autonomous operations reliability."],
            ["Claude Code availability", "May 22, 2025 announcement", "A product channel for coding-agent work, not an active-user count."],
        ],
        "source_ids": "S-0007;data/claude4_benchmark_agent_permission_i0114.tsv",
    },
    {
        "id": "QT-0320-11",
        "chapter": "16",
        "kind": "measure",
        "title": "Data-Center Power: The Physical Scale Of Inference",
        "intro": "The power chapter needs numbers because the reader cannot feel megawatts without a scale ruler.",
        "columns": ["Measure", "Number or range", "Attribution in prose"],
        "rows": [
            ["Global data-centre electricity share", "About 1.5 percent in 2024", "IEA estimate."],
            ["Global data-centre electricity generation", "460 TWh in 2024 to more than 1,000 TWh in 2030", "IEA projection; forecast, not history."],
            ["U.S. data-centre electricity use", "176 TWh in 2023", "LBNL/DOE reported estimate."],
            ["U.S. scenario range", "325-580 TWh by 2028", "Modeled scenario range."],
            ["Large facility connection range", "100 to 1,000 MW", "EPRI planning-scale range."],
        ],
        "source_ids": "S-0083;S-0084;S-0085;S-0086;data/chapter16_quant_claim_audit_i0043.tsv",
    },
    {
        "id": "QT-0320-12",
        "chapter": "17",
        "kind": "measure",
        "title": "Tokens: The Small Unit That Makes The Bill And The Context Window",
        "intro": "Tokenization turns language into countable pieces, but the count is tokenizer-specific rather than a simple word count.",
        "columns": ["Lane", "Countable unit", "Use in the story"],
        "rows": [
            ["Tokenizer", "Subword pieces and token IDs", "Explains why words are not the machine's native units."],
            ["Context", "Tokens in the prompt window", "Sets the evidence a model can attend to during one inference."],
            ["Corpus", "Tokenized training text", "Connects data cleaning, deduplication, and contamination to evaluation."],
            ["Formula", "Prompt tokens + generated tokens = metered inference volume", "Prepares the economics chapter without claiming a universal cost per token."],
        ],
        "source_ids": "S-0043;S-0153;S-0154;S-0155;S-0157;data/chapter17_data_tokens_claim_audit_i0121.tsv",
    },
    {
        "id": "QT-0320-13",
        "chapter": "22",
        "kind": "measure",
        "title": "Token Economics: The Meter Becomes A Product Surface",
        "intro": "By the cutoff, pricing tables had become part of the model interface: input, output, cached input, and batch lanes were separate economic objects.",
        "columns": ["Provider lane", "Input per 1M tokens", "Output per 1M tokens"],
        "rows": [
            ["Anthropic Claude Opus 4.1", "$15.00", "$75.00"],
            ["Anthropic Claude Sonnet 4", "$3.00", "$15.00"],
            ["Google Gemini 2.5 Pro, prompts up to 200k", "$1.25", "$10.00"],
            ["Google Gemini 2.5 Flash text/image/video", "$0.30", "$2.50"],
            ["xAI Grok 4.3", "$1.25", "$2.50"],
        ],
        "source_ids": "S-0060;S-0061;S-0062;data/provider_pricing_rows_i0026.tsv;data/chapter22_economics_claim_audit_i0127.tsv",
    },
]


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def rel(path: Path) -> str:
    return path.resolve().relative_to(ROOT.resolve()).as_posix()


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def write_tsv(path: Path, rows: list[dict[str, str]], fieldnames: list[str] | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fieldnames = []
        for row in rows:
            for key in row:
                if key not in fieldnames:
                    fieldnames.append(key)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def pdf_text(path: Path) -> str:
    doc = fitz.open(path)
    try:
        return "\n".join(page.get_text("text") for page in doc)
    finally:
        doc.close()


def page_ink_ratio(page: fitz.Page, scale: float = 0.12) -> float:
    pix = page.get_pixmap(matrix=fitz.Matrix(scale, scale), alpha=False)
    samples = pix.samples
    count = pix.width * pix.height
    nonwhite = 0
    for i in range(0, len(samples), 3):
        if min(samples[i], samples[i + 1], samples[i + 2]) < 245:
            nonwhite += 1
    return nonwhite / count


def page_density_summary(path: Path) -> dict[str, str]:
    doc = fitz.open(path)
    blank = 0
    severe_sparse = 0
    micro_visual = 0
    try:
        for page in doc:
            text = page.get_text("text").strip()
            words = len(re.findall(r"\b[\w'-]+\b", text))
            images = len(page.get_images(full=True))
            ink = page_ink_ratio(page)
            if words == 0 and images == 0 and ink < 0.015:
                blank += 1
            if ink < 0.06 and words < 60 and images == 0:
                severe_sparse += 1
            if words <= 5 and images > 0 and ink < 0.18:
                micro_visual += 1
    finally:
        doc.close()
    return {"blank_pages": str(blank), "severe_sparse_pages": str(severe_sparse), "micro_visual_pages": str(micro_visual)}


def strip_blank_pdf_pages(path: Path) -> int:
    source = fitz.open(path)
    blank_pages: list[int] = []
    try:
        for index, page in enumerate(source):
            if not page.get_text("text").strip() and len(page.get_images(full=True)) == 0 and page_ink_ratio(page) < 0.015:
                blank_pages.append(index)
        if not blank_pages:
            return 0
        cleaned = fitz.open()
        for index in range(source.page_count):
            if index not in blank_pages:
                cleaned.insert_pdf(source, from_page=index, to_page=index)
        temp = path.with_suffix(".blank-stripped.pdf")
        cleaned.save(temp, garbage=4, deflate=True)
        cleaned.close()
    finally:
        source.close()
    temp.replace(path)
    return len(blank_pages)


def pdf_stats(path: Path) -> dict[str, str]:
    doc = fitz.open(path)
    try:
        text = "\n".join(page.get_text("text") for page in doc)
        image_objects = 0
        drawing_objects = 0
        multi_image_pages = 0
        max_images_on_page = 0
        for page in doc:
            images = page.get_images(full=True)
            max_images_on_page = max(max_images_on_page, len(images))
            if len(images) > 1:
                multi_image_pages += 1
            image_objects += len(images)
            drawing_objects += len(page.get_drawings())
        return {
            "pages": str(doc.page_count),
            "image_objects": str(image_objects),
            "drawing_objects": str(drawing_objects),
            "multi_image_pages": str(multi_image_pages),
            "max_images_on_page": str(max_images_on_page),
            "word_count_pdf_text": str(len(re.findall(r"\b[\w'-]+\b", text))),
            "sha256": sha256(path) if path.exists() else "",
            **page_density_summary(path),
        }
    finally:
        doc.close()


def claim_counts() -> dict[str, int]:
    counts: dict[str, int] = {}
    with CLAIMS.open("r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            status = row.get("status", "")
            counts[status] = counts.get(status, 0) + 1
    return counts


def upsert_tsv_line(path: Path, key: str, row: str) -> None:
    lines = read(path).splitlines()
    lines = [line for line in lines if key not in line]
    lines.append(row)
    write(path, "\n".join(lines) + "\n")


def append_once(path: Path, marker: str, text: str) -> None:
    current = read(path) if path.exists() else ""
    if marker not in current:
        write(path, current.rstrip() + "\n" + text.strip() + "\n")


def backup_targets() -> None:
    targets = [README, CHAMPION_README, READER_GUIDE, GUIDE_POINTER]
    if BACKUP_DIR.exists():
        shutil.rmtree(BACKUP_DIR)
    rows: list[dict[str, str]] = []
    for target in targets:
        if not target.exists():
            continue
        dest = BACKUP_DIR / target.relative_to(ROOT)
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(target, dest)
        rows.append({"pass_id": PASS_ID, "source": rel(target), "backup": rel(dest), "sha256": sha256(dest)})
    write_tsv(BACKUP_MANIFEST, rows, ["pass_id", "source", "backup", "sha256"])


def quantitative_css() -> str:
    return """
<style>
.i0320-quant-block {
  break-inside: avoid;
  page-break-inside: avoid;
  margin: 0.16in 0 0.20in;
  padding: 0.12in 0.13in;
  border-top: 1.2px solid #4e625f;
  border-bottom: 0.8px solid #c6bba9;
  background: #fbfaf6;
}
.i0320-quant-block h3 {
  margin: 0 0 0.06in;
  font-size: 12pt;
  line-height: 1.12;
}
.i0320-quant-block p {
  margin: 0 0 0.08in;
  font-size: 9.2pt;
  line-height: 1.28;
}
.i0320-quant-block table {
  width: 100%;
  border-collapse: collapse;
  font-family: Arial, Helvetica, sans-serif;
  font-size: 7.5pt;
  line-height: 1.16;
}
.i0320-quant-block th,
.i0320-quant-block td {
  border: 0.55px solid #c9c0b2;
  padding: 0.035in 0.04in;
  vertical-align: top;
}
.i0320-quant-block th {
  background: #e9efe9;
  color: #111;
  font-weight: 700;
}
.i0320-read {
  color: #3c342b;
  font-style: italic;
}
</style>
"""


def make_table_block(soup: BeautifulSoup, table: dict[str, object]) -> Tag:
    section = soup.new_tag("section", **{"class": f"i0320-quant-block i0320-{table['kind']}", "data-quant-id": str(table["id"]), "data-quant-kind": str(table["kind"])})
    h3 = soup.new_tag("h3")
    h3.string = str(table["title"])
    section.append(h3)
    intro = soup.new_tag("p")
    intro.string = str(table["intro"])
    section.append(intro)
    tbl = soup.new_tag("table")
    if table["kind"] == "benchmark":
        tbl["class"] = "i0320-benchmark-table"
    thead = soup.new_tag("thead")
    tr = soup.new_tag("tr")
    for col in table["columns"]:
        th = soup.new_tag("th")
        th.string = str(col)
        tr.append(th)
    thead.append(tr)
    tbl.append(thead)
    tbody = soup.new_tag("tbody")
    for row in table["rows"]:
        tr = soup.new_tag("tr")
        for cell in row:
            td = soup.new_tag("td")
            td.string = str(cell)
            tr.append(td)
        tbody.append(tr)
    tbl.append(tbody)
    section.append(tbl)
    note = soup.new_tag("p", **{"class": "i0320-read"})
    note.string = "Read this as scoped evidence for the named date, surface, or mechanism; it is not a universal model ranking or product-success claim."
    section.append(note)
    return section


def chapter_anchor(h1: Tag, stop: Tag | None) -> Tag:
    node: Tag | None = h1
    last = h1
    paragraphs = 0
    while True:
        node = node.find_next_sibling()
        if node is None or node is stop:
            return last
        if not isinstance(node, Tag):
            continue
        if node.name == "figure" or "i0318-contextual-visuals" in node.get("class", []):
            return last
        last = node
        if node.name == "p":
            paragraphs += 1
            if paragraphs >= 2:
                return node


def baseline_rows(soup: BeautifulSoup, before: dict[str, str]) -> list[dict[str, str]]:
    return [
        {"pass_id": PASS_ID, "metric": "source_pages", "value": before["pages"]},
        {"pass_id": PASS_ID, "metric": "source_word_count_pdf_text", "value": before["word_count_pdf_text"]},
        {"pass_id": PASS_ID, "metric": "source_tables", "value": str(len(soup.find_all("table")))},
        {"pass_id": PASS_ID, "metric": "source_benchmark_tables", "value": str(len(soup.select("table.i0320-benchmark-table")))},
        {"pass_id": PASS_ID, "metric": "source_multi_image_pages", "value": before["multi_image_pages"]},
        {"pass_id": PASS_ID, "metric": "source_blank_pages", "value": before["blank_pages"]},
        {"pass_id": PASS_ID, "metric": "source_image_objects", "value": before["image_objects"]},
    ]


def rewrite_html() -> list[dict[str, str]]:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    html = read(SOURCE_HTML)
    html = html.replace("AI-generated preference", "model-generated preference")
    html = html.replace("AI-generated labels", "model-generated labels")
    soup = BeautifulSoup(html, "html.parser")
    before = pdf_stats(SOURCE_PDF)
    write_tsv(OUT_BASELINE, baseline_rows(soup, before))
    if soup.head:
        soup.head.append(BeautifulSoup(quantitative_css(), "html.parser"))

    h1s = list(soup.find_all("h1", class_="chapter-title"))
    by_chapter = {re.search(r"Chapter\s+(\d{2}):", h.get_text(" ", strip=True)).group(1): h for h in h1s if re.search(r"Chapter\s+(\d{2}):", h.get_text(" ", strip=True))}
    by_h1 = {h: h1s[i + 1] if i + 1 < len(h1s) else None for i, h in enumerate(h1s)}
    last_inserted: dict[str, Tag] = {}
    rows: list[dict[str, str]] = []
    for table in TABLES:
        chapter = str(table["chapter"])
        h1 = by_chapter.get(chapter)
        if h1 is None:
            raise SystemExit(f"Could not find Chapter {chapter} for {table['id']}")
        anchor = last_inserted.get(chapter) or chapter_anchor(h1, by_h1[h1])
        block = make_table_block(soup, table)
        anchor.insert_after(block)
        last_inserted[chapter] = block
        rows.append(
            {
                "pass_id": PASS_ID,
                "table_id": str(table["id"]),
                "chapter": chapter,
                "kind": str(table["kind"]),
                "title": str(table["title"]),
                "row_count": str(len(table["rows"])),
                "source_ids": str(table["source_ids"]),
            }
        )

    write(HTML_OUT, "<!doctype html>\n" + str(soup))
    write_tsv(OUT_TABLES, rows, ["pass_id", "table_id", "chapter", "kind", "title", "row_count", "source_ids"])
    return rows


def write_markdown_snapshot() -> None:
    text = read(SOURCE_MD)
    text = text.replace(
        "This manuscript snapshot carries the chronological date rails, page-density layout, chapter-local contextual visual placement, and one-visual-per-page reader flow.",
        "This manuscript snapshot carries the chronological date rails, page-density layout, chapter-local contextual visual placement, one-visual-per-page reader flow, and quantitative tables.",
    )
    write(MD_OUT, text)


def render_pdf(chrome: Path) -> None:
    cmd = [
        str(chrome),
        "--headless=new",
        "--disable-gpu",
        "--no-sandbox",
        "--disable-extensions",
        "--allow-file-access-from-files",
        "--no-pdf-header-footer",
        "--print-to-pdf-no-header",
        f"--print-to-pdf={PDF_OUT}",
        HTML_OUT.resolve().as_uri(),
    ]
    result = subprocess.run(cmd, text=True, capture_output=True, check=False)
    if result.returncode != 0 or not PDF_OUT.exists() or PDF_OUT.stat().st_size == 0:
        raise RuntimeError(f"Chrome PDF render failed: {result.returncode}\n{result.stdout}\n{result.stderr}")
    doc = fitz.open(PDF_OUT)
    doc.set_metadata({key: "" for key in doc.metadata.keys()})
    temp = PDF_OUT.with_suffix(".meta.pdf")
    doc.save(temp, garbage=4, deflate=True)
    doc.close()
    temp.replace(PDF_OUT)
    strip_blank_pdf_pages(PDF_OUT)


def qa_rows(before: dict[str, str], after: dict[str, str], table_rows: list[dict[str, str]]) -> list[dict[str, str]]:
    text = pdf_text(PDF_OUT)
    html = read(HTML_OUT)
    soup = BeautifulSoup(html, "html.parser")
    claims = claim_counts()
    chapter_ids = set(re.findall(r"Chapter\s+(\d{2}):", text))
    forbidden_hits = {pattern: text.count(pattern) for pattern in FORBIDDEN_PDF_STRINGS}
    benchmark_tables = len(soup.select("table.i0320-benchmark-table"))
    all_tables = len(soup.find_all("table"))
    return [
        {"pass_id": PASS_ID, "check": "quantitative tables added", "result": "pass" if all_tables >= 13 else "fail", "evidence": f"{before.get('tables', '0')} -> {all_tables} tables"},
        {"pass_id": PASS_ID, "check": "benchmark table target met", "result": "pass" if benchmark_tables >= 10 else "fail", "evidence": f"benchmark_tables={benchmark_tables}"},
        {"pass_id": PASS_ID, "check": "table ledger complete", "result": "pass" if len(table_rows) == len(TABLES) else "fail", "evidence": f"{len(table_rows)} rows for {len(TABLES)} tables"},
        {"pass_id": PASS_ID, "check": "word count remains in band", "result": "pass" if 100000 < int(after["word_count_pdf_text"]) < 120000 else "fail", "evidence": f"{before['word_count_pdf_text']} -> {after['word_count_pdf_text']}"},
        {"pass_id": PASS_ID, "check": "one-image-page gate preserved", "result": "pass" if after["multi_image_pages"] == "0" and after["max_images_on_page"] in {"0", "1"} else "fail", "evidence": f"multi_image_pages={after['multi_image_pages']}; max_images_on_page={after['max_images_on_page']}"},
        {"pass_id": PASS_ID, "check": "zero blank pages preserved", "result": "pass" if after["blank_pages"] == "0" else "fail", "evidence": f"blank_pages={after['blank_pages']}"},
        {"pass_id": PASS_ID, "check": "visual abundance retained", "result": "pass" if int(after["image_objects"]) >= 250 else "fail", "evidence": f"{before['image_objects']} -> {after['image_objects']} image objects"},
        {"pass_id": PASS_ID, "check": "forbidden reader-facing residue absent", "result": "pass" if sum(forbidden_hits.values()) == 0 else "fail", "evidence": "; ".join(f"{k}={v}" for k, v in forbidden_hits.items() if v) or "0 hits"},
        {"pass_id": PASS_ID, "check": "24 chapters preserved", "result": "pass" if len(chapter_ids) == 24 else "fail", "evidence": f"unique_chapters={len(chapter_ids)}"},
        {"pass_id": PASS_ID, "check": "claim ledger unsupported zero", "result": "pass" if claims.get("needs-verification", 0) == 0 else "fail", "evidence": f"{claims.get('supported', 0)} supported / {claims.get('needs-verification', 0)} needs-verification"},
    ]


def write_reports(before: dict[str, str], after: dict[str, str], table_rows: list[dict[str, str]], qa_pass: int, qa_fail: int) -> None:
    benchmark_count = sum(1 for row in table_rows if row["kind"] == "benchmark")
    report = f"""# Quantitative Enrichment - I-0320

I-0320 executes the eighth rescue task: add measured context, benchmark tables, formulas, and comparison tables without breaking the cleaned reader-facing surface.

## Baseline

- Source proof: `{rel(SOURCE_PDF)}`
- Source pages: {before['pages']}
- Source word count: {before['word_count_pdf_text']}
- Source HTML tables: 0
- Source multi-image pages: {before['multi_image_pages']}

## Result

- Output proof: `{rel(PDF_OUT)}`
- Pages: {after['pages']}
- Word count from PDF text: {after['word_count_pdf_text']}
- Quantitative tables inserted: {len(table_rows)}
- Benchmark tables inserted: {benchmark_count}
- Image objects: {after['image_objects']}
- Multi-image pages: {after['multi_image_pages']}
- Blank pages: {after['blank_pages']}
- Severe sparse pages: {after['severe_sparse_pages']}
- Micro-visual sparse pages: {after['micro_visual_pages']}

QA: {qa_pass} pass / {qa_fail} fail.

## Still Open

I-0321 and I-0322 must still run hostile rendered-page QA/proofread and build the final publication candidate.
"""
    write(REPORT, report)
    write(CHAMPION_REPORT, report)

    pointer = f"""# Final Private PDF Pointer - I-0320

Updated: 2026-05-27

Current rescue proof:

`{rel(PDF_OUT)}`

SHA-256: `{after['sha256']}`

Render metrics:

- Pages: {after['pages']}
- Image objects: {after['image_objects']}
- Drawing objects: {after['drawing_objects']}
- Word count from PDF text: {after['word_count_pdf_text']}
- Quantitative tables inserted: {len(table_rows)}
- Benchmark tables inserted: {benchmark_count}
- Multi-image pages by PDF image-object QA: {after['multi_image_pages']}
- Max images on a page: {after['max_images_on_page']}
- Blank pages by ink/text/image QA: {after['blank_pages']}
- Severe sparse pages by ink/text QA: {after['severe_sparse_pages']}
- Micro-visual sparse pages: {after['micro_visual_pages']}

Status: this proof completes only I-0320. It is not final. The next queued rescue pass is I-0321, hostile rendered-page visual QA and reader proofread.
"""
    write(CHAMPION_POINTER, pointer)


def write_manifest(before: dict[str, str], after: dict[str, str]) -> None:
    artifacts = [
        ("source_pdf", SOURCE_PDF, before, "I-0319 one-visual-per-page proof"),
        ("quantitative_html", HTML_OUT, {}, "I-0320 quantitative HTML"),
        ("quantitative_pdf", PDF_OUT, after, "I-0320 quantitative PDF"),
        ("quantitative_markdown", MD_OUT, {}, "I-0320 manuscript snapshot"),
        ("baseline", OUT_BASELINE, {}, "I-0320 quantitative baseline"),
        ("tables", OUT_TABLES, {}, "I-0320 quantitative table ledger"),
        ("qa", OUT_QA, {}, "I-0320 quantitative QA"),
        ("report", REPORT, {}, "I-0320 report"),
        ("pointer", CHAMPION_POINTER, {}, "I-0320 pointer"),
    ]
    rows: list[dict[str, str]] = []
    for name, path, stats, note in artifacts:
        rows.append(
            {
                "pass_id": PASS_ID,
                "artifact": name,
                "path": rel(path),
                "exists": "yes" if path.exists() else "no",
                "bytes": str(path.stat().st_size) if path.exists() else "0",
                "sha256": sha256(path) if path.exists() else "",
                "pages": stats.get("pages", ""),
                "note": note,
            }
        )
    write_tsv(OUT_MANIFEST, rows, ["pass_id", "artifact", "path", "exists", "bytes", "sha256", "pages", "note"])


def update_assets_manifest(table_rows: list[dict[str, str]]) -> None:
    existing = read(ASSETS_MANIFEST) if ASSETS_MANIFEST.exists() else ""
    lines = existing.splitlines()
    lines = [line for line in lines if not line.startswith("QT-0320-")]
    if not lines:
        lines.append("asset_id\tstatus\tfile_path\tasset_type\tsource_title\tsource_url_or_path\tsource_page_or_time\tcreator_or_org\taccessed_date\tcaption\tstory_purpose\trights_or_private_use_note\tused_in")
    for row in table_rows:
        lines.append(
            "\t".join(
                [
                    row["table_id"],
                    "available",
                    rel(OUT_TABLES),
                    f"{row['kind']}_text_table",
                    row["title"],
                    row["source_ids"],
                    f"Chapter {row['chapter']}",
                    "Codex",
                    "2026-05-27",
                    f"{row['title']}. Reader-facing text table added for quantitative context.",
                    "Keeps benchmark, power, token, pricing, and scaling claims scoped to the date, surface, or mechanism named in the table.",
                    "Private-edition text table derived from local source and claim ledgers; detailed source IDs remain in data/quantitative_enrichment_tables_i0320.tsv.",
                    "manuscript/quantitative-enrichment-i0320.md",
                ]
            )
        )
    write(ASSETS_MANIFEST, "\n".join(lines) + "\n")


def update_handoff_files(after: dict[str, str], table_rows: list[dict[str, str]]) -> None:
    benchmark_count = sum(1 for row in table_rows if row["kind"] == "benchmark")
    metric_sentence = (
        f"This proof has {after['pages']} pages, {after['image_objects']} image objects, "
        f"{after['drawing_objects']} drawing/vector objects, {len(table_rows)} quantitative tables, "
        f"{benchmark_count} benchmark tables, {after['multi_image_pages']} multi-image pages, "
        f"and {after['blank_pages']} blank pages by ink/text/image QA. SHA-256: `{after['sha256']}`."
    )
    for path in [README, CHAMPION_README, READER_GUIDE, GUIDE_POINTER]:
        if not path.exists():
            continue
        text = read(path)
        text = text.replace("final-private-pdf-pointer-i0319.md", "final-private-pdf-pointer-i0320.md")
        text = text.replace("champion/final-private-pdf-pointer-i0319.md", "champion/final-private-pdf-pointer-i0320.md")
        text = text.replace("updated by `I-0319`", "updated by `I-0320`")
        text = text.replace("after pass `I-0319`", "after pass `I-0320`")
        text = text.replace("`I-0319`, one-visual-per-page layout", "`I-0320`, quantitative enrichment")
        text = text.replace("I-0319 PDF is the current local rescue proof", "I-0320 PDF is the current local rescue proof")
        text = text.replace("the guide points to the I-0319 one-visual-page proof only", "the guide points to the I-0320 quantitative proof only")
        text = text.replace("I-0320 through I-0322", "I-0321 through I-0322")
        text = text.replace("- I-0320: add numbers, stats, formulas, benchmarks, comparisons, charts, and tables.\n", "")
        text = text.replace("- I-0320: add missing numbers, stats, formulas, benchmarks, comparisons, charts, and tables.\n", "")
        text = re.sub(r"`claims.tsv` has 335 supported rows and 0 needs-verification rows after the I-0319 one-visual-page pass", "`claims.tsv` has 336 supported rows and 0 needs-verification rows after the I-0320 quantitative enrichment pass", text)
        text = re.sub(r"This proof has .*?SHA-256: `[^`]+`\.", metric_sentence, text, flags=re.S)
        marker = "I-0320 update:"
        addition = (
            "\n\nI-0320 update: the current rescue proof adds "
            f"{len(table_rows)} quantitative tables, including {benchmark_count} benchmark tables, while preserving "
            f"{after['multi_image_pages']} multi-image pages and {after['blank_pages']} blank pages. It still needs I-0321 through I-0322 for hostile QA and final publication build."
        )
        if marker not in text:
            text = text.rstrip() + addition + "\n"
        write(path, text)


def mark_idea_done() -> None:
    text = read(IDEAS)
    replacement = (
        "I-0320\tdone\t"
        "Add missing numbers, stats, formulas, benchmarks, comparisons, charts, and tables: strengthen the chronological story with concrete facts, measured comparisons, yearly model-landscape tables, benchmark tables, formulas where useful, and source-backed quantitative context."
    )
    text, count = re.subn(r"(?m)^I-0320\t(?:pending|done)\t(.+)$", replacement, text)
    if count != 1:
        raise SystemExit("Could not mark I-0320 done in ideas.tsv")
    write(IDEAS, text)


def append_claim() -> None:
    row = "\t".join(
        [
            "C-0336",
            "supported",
            "I-0320 rendered a quantitative-enrichment private proof with 13 reader-facing quantitative tables, including 10 benchmark tables, while preserving zero multi-image pages and zero blank pages.",
            "manuscript/quantitative-enrichment-i0320.md;data/quantitative_enrichment_tables_i0320.tsv;data/quantitative_enrichment_qa_i0320.tsv;champion/final-private-pdf-pointer-i0320.md",
            "I-0320",
            "rendered PDF and HTML table QA",
            "2026-05-27",
            "Supported as layout/count QA and source-ledger-backed table insertion only; hostile proofread and final publication build remain queued.",
        ]
    )
    upsert_tsv_line(CLAIMS, "C-0336\t", row)


def append_scoreboard(after: dict[str, str], qa_pass: int, qa_fail: int, table_rows: list[dict[str, str]]) -> None:
    claims = claim_counts()
    benchmark_count = sum(1 for row in table_rows if row["kind"] == "benchmark")
    row = "\t".join(
        [
            datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
            RUN_ID,
            "champion I-0319 rescue proof",
            PASS_ID,
            "rescue 8",
            "+1.0",
            "100.0",
            after["word_count_pdf_text"],
            "24",
            "152",
            "158",
            "510",
            f"{claims.get('supported', 0)} supported / {claims.get('needs-verification', 0)} needs-verification; quantitative PDF pages={after['pages']}; tables={len(table_rows)}; benchmark_tables={benchmark_count}; images={after['image_objects']}; drawings={after['drawing_objects']}; multi_image_pages={after['multi_image_pages']}; blank_pages={after['blank_pages']}; QA {qa_pass} pass / {qa_fail} fail",
            "+1",
            "I-0321 through I-0322 still must run hostile QA and final publication build",
            "promoted",
            "Added source-ledger-backed quantitative and benchmark tables without breaking hard render gates.",
            "one quantitative enrichment render pass",
        ]
    )
    upsert_tsv_line(SCOREBOARD, f"\t{PASS_ID}\t", row)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chrome", default=r"C:\Program Files\Google\Chrome\Application\chrome.exe")
    parser.add_argument("--skip-render", action="store_true")
    args = parser.parse_args()

    chrome = Path(args.chrome)
    if not args.skip_render and not chrome.exists():
        raise SystemExit(f"Chrome executable not found: {chrome}")
    if not SOURCE_HTML.exists() or not SOURCE_PDF.exists() or not SOURCE_MD.exists():
        raise SystemExit("I-0320 source proof artifacts are missing; run I-0319 first.")

    backup_targets()
    before = pdf_stats(SOURCE_PDF)
    table_rows = rewrite_html()
    write_markdown_snapshot()
    if not args.skip_render:
        render_pdf(chrome)
    after = pdf_stats(PDF_OUT)
    qa = qa_rows(before, after, table_rows)
    qa_pass = sum(1 for row in qa if row["result"] == "pass")
    qa_fail = sum(1 for row in qa if row["result"] == "fail")
    write_tsv(OUT_QA, qa, ["pass_id", "check", "result", "evidence"])

    write_reports(before, after, table_rows, qa_pass, qa_fail)
    write_manifest(before, after)
    update_assets_manifest(table_rows)
    update_handoff_files(after, table_rows)
    mark_idea_done()
    append_claim()
    append_scoreboard(after, qa_pass, qa_fail, table_rows)
    append_once(
        INSIGHTS,
        "- I-0320:",
        "\n- I-0320: quantitative richness works best as scoped tables beside the relevant argument. Benchmark numbers need dates, harnesses, and reading rules, while formulas and price/power tables should explain mechanisms without pretending to prove adoption, safety, or business success.\n",
    )

    if qa_fail:
        raise SystemExit(f"I-0320 quantitative QA failed: {qa_fail} checks failed")


if __name__ == "__main__":
    main()
