from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path


PASS_ID = "I-0244"
ROOT = Path(__file__).resolve().parents[1]
OUT_TSV = ROOT / "data" / "source_card_quote_extraction_i0244.tsv"
SUMMARY_TSV = ROOT / "data" / "source_card_quote_extraction_summary_i0244.tsv"
BRIEF_MD = ROOT / "manuscript" / "source-card-quote-extraction-i0244.md"


ROWS = [
    {
        "extraction_id": "SCQ-0244-001",
        "parent_card_id": "SEC-0189-009",
        "chapter": "6",
        "source_id": "S-0074",
        "source_title": "Aligning language models to follow instructions",
        "card_status": "quote_safe_ready",
        "quote_text": "following user intentions",
        "quote_words": "3",
        "provenance_anchor": "SNAP-20260525-016 line 50",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0074__product-post__instruction-following__text-render.md:50",
        "paraphrase_final_label": "InstructGPT reframed GPT-3 behavior around following user intent.",
        "blocked_claims": "No solved alignment, safety, or customer-task success claim.",
        "placement_note": "Use as a small RLHF/product-transition source card, not as a chapter epigraph.",
    },
    {
        "extraction_id": "SCQ-0244-002",
        "parent_card_id": "SEC-0189-009",
        "chapter": "6",
        "source_id": "S-0074",
        "source_title": "Aligning language models to follow instructions",
        "card_status": "quote_safe_ready",
        "quote_text": "rather than to safely perform",
        "quote_words": "5",
        "provenance_anchor": "SNAP-20260525-016 line 192",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0074__product-post__instruction-following__text-render.md:192",
        "paraphrase_final_label": "OpenAI contrasted next-word training with safely performing the user's task.",
        "blocked_claims": "Do not generalize this contrast to every lab or later model family.",
        "placement_note": "Use beside a training-objective source card if the prose needs a sharp distinction.",
    },
    {
        "extraction_id": "SCQ-0244-003",
        "parent_card_id": "SEC-0189-009",
        "chapter": "6",
        "source_id": "S-0074",
        "source_title": "Aligning language models to follow instructions",
        "card_status": "quote_safe_ready",
        "quote_text": "provide demonstrations",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-016 line 194",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0074__product-post__instruction-following__text-render.md:194",
        "paraphrase_final_label": "Labelers demonstrated desired behavior and ranked outputs in the RLHF process.",
        "blocked_claims": "No claim that labelers represented all users or values.",
        "placement_note": "Use as a process tile paired with a ranking-output paraphrase.",
    },
    {
        "extraction_id": "SCQ-0244-004",
        "parent_card_id": "SEC-0189-009",
        "chapter": "6",
        "source_id": "S-0074",
        "source_title": "Aligning language models to follow instructions",
        "card_status": "quote_safe_ready",
        "quote_text": "default language models",
        "quote_words": "3",
        "provenance_anchor": "SNAP-20260525-016 line 198",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0074__product-post__instruction-following__text-render.md:198",
        "paraphrase_final_label": "OpenAI said InstructGPT models became the default language models on its API.",
        "blocked_claims": "Keep deployment scope limited to the OpenAI API at the source date.",
        "placement_note": "Use for the product handoff from research method to API behavior.",
    },
    {
        "extraction_id": "SCQ-0244-005",
        "parent_card_id": "SEC-0189-009",
        "chapter": "6",
        "source_id": "S-0074",
        "source_title": "Aligning language models to follow instructions",
        "card_status": "quote_safe_ready",
        "quote_text": "alignment tax",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-016 line 288",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0074__product-post__instruction-following__text-render.md:288",
        "paraphrase_final_label": "The source names a tradeoff between customer-task alignment and some academic NLP tasks.",
        "blocked_claims": "No universal law of alignment cost or model capability tradeoff.",
        "placement_note": "Use as a caveat tile, not as proof of a fixed tax.",
    },
    {
        "extraction_id": "SCQ-0244-006",
        "parent_card_id": "SEC-0189-009",
        "chapter": "6",
        "source_id": "S-0074",
        "source_title": "Aligning language models to follow instructions",
        "card_status": "quote_safe_ready",
        "quote_text": "far from fully aligned",
        "quote_words": "4",
        "provenance_anchor": "SNAP-20260525-016 line 298",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0074__product-post__instruction-following__text-render.md:298",
        "paraphrase_final_label": "OpenAI's own post kept a limitation caveat visible.",
        "blocked_claims": "No safety-proof, solved-values, or no-risk claim.",
        "placement_note": "Use as the safety humility footer for the Chapter 6 card cluster.",
    },
    {
        "extraction_id": "SCQ-0244-007",
        "parent_card_id": "SEC-0189-010",
        "chapter": "6",
        "source_id": "S-0075",
        "source_title": "Model Spec (2024/05/08)",
        "card_status": "quote_safe_ready",
        "quote_text": "desired behavior",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-005 line 629",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0075__behavior-specification__openai-model-spec-2024-05-08__html.html:629",
        "paraphrase_final_label": "The Model Spec is a behavior-specification source, not a proof that behavior always follows the spec.",
        "blocked_claims": "No compliance, safety, or universal-assistant-behavior claim.",
        "placement_note": "Use as a specification card after the RLHF process card.",
    },
    {
        "extraction_id": "SCQ-0244-008",
        "parent_card_id": "SEC-0189-010",
        "chapter": "6",
        "source_id": "S-0075",
        "source_title": "Model Spec (2024/05/08)",
        "card_status": "quote_safe_ready",
        "quote_text": "objectives, rules, and defaults",
        "quote_words": "4",
        "provenance_anchor": "SNAP-20260525-005 lines 633-634",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0075__behavior-specification__openai-model-spec-2024-05-08__html.html:633",
        "paraphrase_final_label": "Assistant behavior is specified through a hierarchy of principles and defaults.",
        "blocked_claims": "Do not imply this exact hierarchy applies to all labs or later revisions.",
        "placement_note": "Use as a compact typography card title.",
    },
    {
        "extraction_id": "SCQ-0244-009",
        "parent_card_id": "SEC-0189-010",
        "chapter": "6",
        "source_id": "S-0075",
        "source_title": "Model Spec (2024/05/08)",
        "card_status": "quote_safe_ready",
        "quote_text": "partial order",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-005 line 635",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0075__behavior-specification__openai-model-spec-2024-05-08__html.html:635",
        "paraphrase_final_label": "The source frames objectives as incomplete preference ordering rather than an executable moral formula.",
        "blocked_claims": "No formal guarantee or complete preference-specification claim.",
        "placement_note": "Use only if the chapter needs a technical aside on conflicting objectives.",
    },
    {
        "extraction_id": "SCQ-0244-010",
        "parent_card_id": "SEC-0189-010",
        "chapter": "6",
        "source_id": "S-0075",
        "source_title": "Model Spec (2024/05/08)",
        "card_status": "quote_safe_ready",
        "quote_text": "rules",
        "quote_words": "1",
        "provenance_anchor": "SNAP-20260525-005 line 636",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0075__behavior-specification__openai-model-spec-2024-05-08__html.html:636",
        "paraphrase_final_label": "Rules are the non-overridable part of the behavior-specification frame.",
        "blocked_claims": "No claim that rules are sufficient for all conflicts.",
        "placement_note": "Use as one small label in a three-part card, not as a standalone quotation.",
    },
    {
        "extraction_id": "SCQ-0244-011",
        "parent_card_id": "SEC-0189-010",
        "chapter": "6",
        "source_id": "S-0075",
        "source_title": "Model Spec (2024/05/08)",
        "card_status": "quote_safe_ready",
        "quote_text": "default behaviors",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-005 line 637",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0075__behavior-specification__openai-model-spec-2024-05-08__html.html:637",
        "paraphrase_final_label": "Defaults are stable behavior templates that can be overridden in some contexts.",
        "blocked_claims": "Do not turn defaults into guarantees of actual model action.",
        "placement_note": "Use with objectives and rules as a three-part behavior-spec source card.",
    },
    {
        "extraction_id": "SCQ-0244-012",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0078",
        "source_title": "Introducing ChatGPT Plus",
        "card_status": "quote_safe_ready",
        "quote_text": "ChatGPT Plus",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-013 lines 39 and 51",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0078__product-post__chatgpt-plus__text-render.md:51",
        "paraphrase_final_label": "The research preview became a paid subscription surface.",
        "blocked_claims": "No adoption count, retention, revenue, or customer productivity claim.",
        "placement_note": "Use as the chapter's productization source card header.",
    },
    {
        "extraction_id": "SCQ-0244-013",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0078",
        "source_title": "Introducing ChatGPT Plus",
        "card_status": "quote_safe_ready",
        "quote_text": "$20/month",
        "quote_words": "1",
        "provenance_anchor": "SNAP-20260525-013 line 51",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0078__product-post__chatgpt-plus__text-render.md:51",
        "paraphrase_final_label": "OpenAI announced a $20/month subscription tier.",
        "blocked_claims": "No revenue, user mix, margin, or conversion-rate claim.",
        "placement_note": "Use only as a dated launch-price surface, not a business-model proof.",
    },
    {
        "extraction_id": "SCQ-0244-014",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0078",
        "source_title": "Introducing ChatGPT Plus",
        "card_status": "quote_safe_ready",
        "quote_text": "Faster response times",
        "quote_words": "3",
        "provenance_anchor": "SNAP-20260525-013 line 54",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0078__product-post__chatgpt-plus__text-render.md:54",
        "paraphrase_final_label": "The subscription promised speed and reliability benefits.",
        "blocked_claims": "No measured latency, uptime, or satisfaction claim.",
        "placement_note": "Use as one bullet in a paid-tier source card.",
    },
    {
        "extraction_id": "SCQ-0244-015",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0078",
        "source_title": "Introducing ChatGPT Plus",
        "card_status": "quote_safe_ready",
        "quote_text": "Priority access",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-013 line 55",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0078__product-post__chatgpt-plus__text-render.md:55",
        "paraphrase_final_label": "The paid tier offered priority access to new features and improvements.",
        "blocked_claims": "No feature-adoption, release-cadence, or user-success claim.",
        "placement_note": "Use only with S-0078 text-render caveat.",
    },
    {
        "extraction_id": "SCQ-0244-016",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0079",
        "source_title": "Introducing ChatGPT Enterprise",
        "card_status": "quote_safe_ready",
        "quote_text": "enterprise-grade security and privacy",
        "quote_words": "4",
        "provenance_anchor": "SNAP-20260525-026 lines 8 and 10",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0079__product-post__chatgpt-enterprise__text-render.md:10",
        "paraphrase_final_label": "OpenAI framed Enterprise around security, privacy, speed, context, analysis, and customization.",
        "blocked_claims": "No neutral enterprise adoption, compliance outcome, or productivity claim.",
        "placement_note": "Use as vendor-attributed launch positioning only.",
    },
    {
        "extraction_id": "SCQ-0244-017",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0079",
        "source_title": "Introducing ChatGPT Enterprise",
        "card_status": "quote_safe_ready",
        "quote_text": "do not train on your business data",
        "quote_words": "7",
        "provenance_anchor": "SNAP-20260525-026 line 18",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0079__product-post__chatgpt-enterprise__text-render.md:18",
        "paraphrase_final_label": "The product page separated business-data controls from the general ChatGPT surface.",
        "blocked_claims": "No independent privacy audit, security effectiveness, or compliance outcome claim.",
        "placement_note": "Use as a source-card footer with vendor attribution visible.",
    },
    {
        "extraction_id": "SCQ-0244-018",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0079",
        "source_title": "Introducing ChatGPT Enterprise",
        "card_status": "quote_safe_ready",
        "quote_text": "admin console",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-026 line 18",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0079__product-post__chatgpt-enterprise__text-render.md:18",
        "paraphrase_final_label": "Enterprise turned ChatGPT into an administered workplace product.",
        "blocked_claims": "No seat count, active-use, deployment success, or customer-side outcome claim.",
        "placement_note": "Use as a product-administration tile.",
    },
    {
        "extraction_id": "SCQ-0244-019",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0079",
        "source_title": "Introducing ChatGPT Enterprise",
        "card_status": "quote_safe_ready",
        "quote_text": "32k context",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-026 line 20",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0079__product-post__chatgpt-enterprise__text-render.md:20",
        "paraphrase_final_label": "OpenAI positioned longer context as part of Enterprise packaging.",
        "blocked_claims": "No current context-window, task success, or productivity inference.",
        "placement_note": "Use only in the 2023 Enterprise launch context.",
    },
    {
        "extraction_id": "SCQ-0244-020",
        "parent_card_id": "SEC-0189-012",
        "chapter": "7",
        "source_id": "S-0079",
        "source_title": "Introducing ChatGPT Enterprise",
        "card_status": "quote_safe_ready",
        "quote_text": "available today",
        "quote_words": "2",
        "provenance_anchor": "SNAP-20260525-026 line 26",
        "local_evidence": "data/source_snapshots/2026-05-25/2026-05-25__S-0079__product-post__chatgpt-enterprise__text-render.md:26",
        "paraphrase_final_label": "The launch page framed Enterprise as available at announcement time.",
        "blocked_claims": "No inference about actual rollout completion, procurement, paid seats, or usage.",
        "placement_note": "Use only as vendor launch-page wording.",
    },
    {
        "extraction_id": "SCQ-0244-021",
        "parent_card_id": "SEC-0189-015",
        "chapter": "15",
        "source_id": "S-0001",
        "source_title": "GTC-2026-Keynote.pdf page 29",
        "card_status": "quote_safe_ready",
        "quote_text": "AI factories are the industrial infrastructure",
        "quote_words": "6",
        "provenance_anchor": "GTC-2026-Keynote.pdf page 29; data/gtc_2026_keynote_page_notes.tsv row 29",
        "local_evidence": "GTC-2026-Keynote.pdf; data/gtc_2026_keynote_page_notes.tsv:29",
        "paraphrase_final_label": "Treat NVIDIA's AI-factory language as source-actor framing.",
        "blocked_claims": "No neutral industry definition, deployed capacity, revenue, or performance proof.",
        "placement_note": "Use as a source-actor card beside independent infrastructure evidence.",
    },
    {
        "extraction_id": "SCQ-0244-022",
        "parent_card_id": "SEC-0189-016",
        "chapter": "15;16",
        "source_id": "S-0001",
        "source_title": "GTC-2026-Keynote.pdf page 51",
        "card_status": "quote_safe_ready",
        "quote_text": "DSX AI Factory Platform",
        "quote_words": "4",
        "provenance_anchor": "GTC-2026-Keynote.pdf page 51; data/gtc_2026_keynote_page_notes.tsv row 51",
        "local_evidence": "GTC-2026-Keynote.pdf; data/gtc_2026_keynote_page_notes.tsv:51",
        "paraphrase_final_label": "Use the DSX slide as an NVIDIA system/facility framing surface.",
        "blocked_claims": "No customer deployment, power solution, adoption, or facility-performance claim.",
        "placement_note": "Use only after deciding whether it duplicates the page-29 AI-factory source card.",
    },
]


FIELDS = [
    "pass_id",
    "extraction_id",
    "parent_card_id",
    "chapter",
    "source_id",
    "source_title",
    "card_status",
    "quote_text",
    "quote_words",
    "provenance_anchor",
    "local_evidence",
    "paraphrase_final_label",
    "blocked_claims",
    "placement_note",
]


def write_tsv(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    rows = [{**{"pass_id": PASS_ID}, **row} for row in ROWS]
    write_tsv(OUT_TSV, rows, FIELDS)
    quote_words_by_source: Counter[str] = Counter()
    status_counts = Counter(row["card_status"] for row in rows)
    parent_counts = Counter(row["parent_card_id"] for row in rows)
    for row in rows:
        quote_words_by_source[row["source_id"]] += int(row["quote_words"])
    summary = [
        {
            "pass_id": PASS_ID,
            "extraction_rows": str(len(rows)),
            "parent_cards_touched": str(len(parent_counts)),
            "chapters_touched": str(len({row["chapter"] for row in rows})),
            "quote_safe_ready_rows": str(status_counts["quote_safe_ready"]),
            "paraphrase_final_ready_rows": str(status_counts["paraphrase_final_ready"]),
            "blocked_needs_anchor_rows": str(status_counts["blocked_needs_anchor"]),
            "max_words_from_one_source": str(max(quote_words_by_source.values())),
            "quote_words_by_source": ";".join(f"{source}:{count}" for source, count in sorted(quote_words_by_source.items())),
        }
    ]
    write_tsv(SUMMARY_TSV, summary, list(summary[0].keys()))
    lines = [
        "# I-0244 Source-Card Quote Extraction",
        "",
        "This pass converts the strongest already-captured source-card candidates into quote-safe extraction rows with exact local line, page, or slide-note anchors.",
        "",
        "## Results",
        "",
        f"- Extraction rows: {len(rows)}",
        f"- Parent source-card candidates touched: {len(parent_counts)}",
        f"- Chapters touched: {len({row['chapter'] for row in rows})}",
        f"- Quote-safe rows: {status_counts['quote_safe_ready']}",
        f"- Rows without direct quotation: {status_counts['paraphrase_final_ready']}",
        f"- Rows still blocked for anchor/page proof: {status_counts['blocked_needs_anchor']}",
        f"- Highest direct-quote word count from any one source in this pass: {max(quote_words_by_source.values())}",
        "",
        "## Source Discipline",
        "",
        "All rows keep quote fragments short and retain blocked-claim language. These are extraction permissions for later source cards, not automatic final-layout approval; final cards still need page proof, note placement, typography QA, and copyright/rights review.",
        "",
        "## Source Word Counts",
        "",
    ]
    for source, count in sorted(quote_words_by_source.items()):
        lines.append(f"- {source}: {count} quoted words")
    lines.append("")
    BRIEF_MD.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"rows={len(rows)} max_words_one_source={max(quote_words_by_source.values())} output={OUT_TSV.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
